media:
  input: public
  output: /

content:
  - name: changenotes
    label: Change Notes
    type: collection
    path: src/content/changenotes
    icon: file-text
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: season
        label: Season
        type: number
        required: true
      - name: body
        label: Content
        type: rich-text
    view:
      fields: [title, date, season]
      sort: [date]
      default:
        sort: date
        order: desc